Twitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.core.urls")),
    path('tweet/', include("apps.tweet.urls")),
    path('user/', include("apps.userprofile.urls")),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
            }),
            
]

apps/core/urls.py
from django.urls import path

# Authentication URLS
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("", views.frontpage, name="frontpage"),
    # Authentication Views
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
]

apps/tweet/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('create/', views.create_tweet, name='create_tweet'),
]

apps/userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("edit/", views.edit_profile, name="edit_profile"),
    path("<str:username>/", views.user_details, name="user_details"),    
]

apps/core/models.py
from django.db import models

apps/tweet/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Tweet(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(max_length=150)
    likes = models.ManyToManyField(get_user_model(), related_name='tweet_user')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.body

apps/userprofile/models.py
from django.db import models
from django.contrib.auth import get_user_model

class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, default="default.jpg")
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False)

    def follow_user(self, to_follow):
        if to_follow != self:
            if to_follow in self.follows.all():
                self.follows.add(to_follow)
                return True
            else:
                self.follows.remove(to_follow)
                return False
        return False


    def __str__(self):
        return self.user.username

apps/tweet/forms.py
from django.forms import ModelForm

from .models import Tweet

class TweetCreationForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ['body']
    

apps/userprofile/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from apps.userprofile.models import UserProfile
from django.contrib.auth.forms import UserCreationForm


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ("avatar",)

        widgets = {
            'avatar': forms.FileInput(attrs={'accept': 'image/*'}),
        }

apps/core/views.py
from django.shortcuts import render

from apps.tweet.models import Tweet
from apps.tweet.forms import TweetCreationForm


def frontpage(request):
    tweets = Tweet.objects.all()
    form = TweetCreationForm()
    return render(request, "core/frontpage.html", {"tweets": tweets, "form": form})

apps/tweet/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from .forms import TweetCreationForm
from .models import Tweet


@login_required
def create_tweet(request: HttpRequest) -> HttpResponseRedirect:
    """
    Create a new tweet.

    Args:
        request: The request object.

    Returns:
        The response redirect object.
    """

    if request.method == "POST":
        form = TweetCreationForm(request.POST)
        if form.is_valid():
            tweet: Tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()
            messages.success(request, "Tweet created.")
            return redirect("frontpage")
    return redirect("frontpage")

@login_required
def delete_tweet(request: HttpRequest, tweet_id:int) -> HttpResponseRedirect:
    """
    Delete a tweet.
    
    Args:
        request: The request object.
        tweet_id: The id of Tweet:
    """            
    tweet: Tweet = get_object_or_404(Tweet, pk=tweet_id, user=request.user)
    tweet.delete()
    return redirect("frontpage")

apps/userprofile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from apps.userprofile.forms import UserProfileForm, UserForm


def user_details(request, username):
    """
    View a user's profile.
    """
    tuser = get_object_or_404(User, username=username)
    return render(request, "userprofile/user_profile.html", {"tuser": tuser})


def signup(request):
    """
    Signup a new user.
    """
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            messages.success(request, "You're now a user! You've been signed in, too.")
            return redirect("userprofile:user_details", new_user.username)
    return render(request, "userprofile/signup.html", {"form": form})


@login_required
def edit_profile(request):
    """
    Edit a user's profile.
    """
    if request.method == "POST":
        uform = UserForm(request.POST, instance=request.user)
        pform = UserProfileForm(
            request.POST, request.FILES, instance=request.user.userprofile
        )
        if uform.is_valid() and pform.is_valid():
            uform.save()
            pform.save()
            messages.success(request, "Profile updated!")
            return redirect("userprofile:edit_profile")
    uform = UserForm(instance=request.user)
    pform = UserProfileForm(instance=request.user.userprofile)
    return render(
        request, "userprofile/edit_profile.html", {"uform": uform, "pform": pform}
    )

apps/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} / Twitter</title>
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/bulma-prefers-dark" />
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
    <link rel="shortcut icon" href="{% static 'twitter_logo.png' %}" type="image/x-png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@4.0.0/animate.min.css" />
    <script src="https://kit.fontawesome.com/bc926fbd0c.js" crossorigin="anonymous"></script>

    <style>
        .profile-img {
            border-radius: 10%;
        }
    </style>
</head>

<body hx-boost="true">
    {% include 'core/islands/navbar.html' %}

    {% block content %}

    {% endblock content %}
    {% include 'core/islands/messages.html' %}

</body>

</html>

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% load bulma_tags %}
{% load humanize %}


{% block title %}
Home
{% endblock title %}


{% block content %}
<div class="container">
    <section class="section">

        <h1 class="title">Home</h1>
        {% include 'tweet/islands/tweet_form.html' %}
        {% for tweet in tweets %}
            {% include 'tweet/islands/tweet.html' %}
        {% endfor %}

    </section>
</div>
{% endblock content %}

apps/core/templates/core/islands/messages.html
{% if messages %}

{% for message in messages %}
<div
    style="width:100%;z-index:99999;position:fixed;pointer-events:none;display:flex;flex-direction:column;padding:15px;bottom:0;left:0;right:0;text-align:center;align-items:center;">
    <div class="notification is-{{ message.tags }} animate__animated animate__slower animate__fadeOut"
        style="width:auto;pointer-events:auto;display:inline-flex;white-space:pre-wrap;opacity:1;"><button
            class="delete"></button>{{message}}</div>
</div>
{% endfor %}

{% endif %}

apps/core/templates/core/islands/navbar.html
{% load static %}

<nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'frontpage' %}">
            <img src="{% static 'twitter_logo.png' %}">
            <h1 class="title has-text-white pl-1 is-hidden-desktop">Twitter</h1>
        </a>

        <a 
        role="button" 
        class="navbar-burger" 
        aria-label="menu" 
        aria-expanded="false" 
        data-target="navbarBasicExample"
        onclick="document.getElementsByClassName('navbar-menu')[0].classList.toggle('is-active') | document.getElementsByClassName('navbar-burger')[0].classList.toggle('is-active')">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'frontpage' %}">
                Home
            </a>

            <a class="navbar-item">
                Documentation
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Jobs
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">

                    {% if user.is_authenticated %}
                    <a href="{% url 'userprofile:user_details' user.username %}" class="button is-ghost">
                        <article class="image is-36x36">
                            <img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }}'s Avatar"
                                class="profile-img" width="100" height="100">
                        </article>
                    </a>
                    <a class="button is-danger" href="{% url 'logout' %}">
                        Log out
                    </a>
                    {% else %}
                    <a class="button is-success" href="{% url 'userprofile:signup' %}">
                        <strong>Sign up</strong>
                    </a>
                    <a class="button is-light" href="{% url 'login' %}">
                        Log in
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

apps/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load bulma_tags %}


{% block title %}
    Login
{% endblock title %}
    

{% block content %}
    <div class="container">
        <section class="section">
            <h1 class="title">Login</h1>
            <form action="." method="post">
                {{form|bulma}}
                {% csrf_token %}
                <button type="submit" class="button is-large">Login</button>
            </form>
        </section>
    </div>
{% endblock content %}
    

apps/tweet/templates/tweet/islands/tweet.html
{% load humanize %}

<div class="card mb-3" id="tweet-{{ tweet.id }}">

    <div class="card-content">
        <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src="{{ tweet.user.userprofile.avatar.url }}" alt="{{tweet.user.username}}" class="profile-img">
                </figure>
            </div>
            <div class="media-content">
                <strong>{{ tweet.user.get_full_name|default:tweet.user.get_username }}</strong>
                <br>
                <a href="{% url 'userprofile:user_details' tweet.user.username %}">@{{ tweet.user.get_username }}</a>
                <small class="tag" title="{{ tweet.created_at }}">{{ tweet.created_at|naturaltime }}</small>
            </div>
        </div>
        <div class="content">
            {{tweet.body|safe}}
            <br>
        </div>
    </div>
    <footer class="card-footer">
        <a href="#tweet-{{ tweet.id }}" class="card-footer-item">View</a>
        <a href="#" class="card-footer-item">Like</a>
        <a href="#" class="card-footer-item">Comment</a>
    </footer>
</div>

apps/tweet/templates/tweet/islands/tweet_form.html
{% load bulma_tags %}

<div class="box">
    {% if user.is_authenticated %}
    <div class="media pb-4">
        <div class="media-left">
            {% if user.userprofile.avatar %}
            <figure class="image is-48x48">
                <img src="{{ user.userprofile.avatar.url }}" alt="{{ user.username }}'s Profile Image" class="profile-img">
            </figure>
        </div>
        <div class="media-content">
            <strong>{{ user.get_full_name|default:user.get_username }}</strong>
            <br>
            <a href="{% url 'userprofile:user_details' user.username %}">@{{ user.get_username }}</a>
        </div>
        <div class="media-right">
            <a href="{% url 'logout' %}" class="button is-danger is-small is-outlined">Logout</a>
        </div>
    </div>
    {% endif %}
    {% endif %}
    <form action="{% url 'create_tweet' %}" method="post" class="form">
        {% csrf_token %}
        <div class="field">
            <div class="control ">
                <textarea 
                name="body" 
                cols="40" 
                rows="10" 
                maxlength="150" 
                class="control textarea" 
                required
                placeholder="What's on your mind?"
                id="id_body"></textarea>
            </div>
        </div>
        <br>
        <button type="submit" class="button is-info is-fullwidth is-large">Tweet</button>
    </form>
</div>

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'core/base.html' %}
{% load bulma_tags %}


{% block title %}
    Edit Profile
{% endblock title %}
    

{% block content %}
    <div class="container">
        <section class="section">
            <h1 class="title">Edit Profile</h1>
            <form action="." method="post">
                {{uform|bulma}}
                {{pform|bulma}}
                {% csrf_token %}
                <button type="submit" class="button is-large">Save</button>
            </form>
        </section>
    </div>
{% endblock content %}
    

apps/userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}
{% load bulma_tags %}


{% block title %}
    Signup
{% endblock title %}
    

{% block content %}
    <div class="container">
        <section class="section">
            <h1 class="title">Signup</h1>
            <form action="." method="post">
                {{form|bulma}}
                {% csrf_token %}
                <button type="submit" class="button is-large">Signup</button>
            </form>
        </section>
    </div>
{% endblock content %}
    

apps/userprofile/templates/userprofile/user_profile.html
{% extends 'core/base.html' %}


{% block title %}
{{ tuser.get_full_name|default:tuser.username }} (@{{tuser.username}})
{% endblock title %}


{% block content %}
<div class="container-fluid">
    <section class="section">
        <div class="columns">
            <div class="column is-8">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-128x128">
                                    <img src="{{ tuser.userprofile.avatar.url }}" alt="User avatar" class="profile-img">
                                </figure>
                            </div>
                            <div class="media-content">
                                <h1 class="title">{{ tuser.get_full_name|default:tuser.username }}</h1>
                                <p class="subtitle">@{{ tuser.username }}</p>
                            </div>
                        </div>
                        <div class="buttons">
                            {% if tuser != user %}
                            <a href="" class="button is-link is-outlined">Follow</a>
                            {% else %}
                            <a href="{% url 'userprofile:edit_profile' %}" class="button">Edit Myself</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <br>
                {% for tweet in tuser.tweet_set.all %}
                {% include 'tweet/islands/tweet.html' %}
                {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock content %}